version: 2
updates:
  # Vigilancia de dependencias Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  # Vigilancia de contenedores (Blockscout Docker)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
